### ISSUE TITLE
No such file or directory: '../asio_c

### ISSUE THREAD

**Issue by niogaoly** [DUOLabs333/vulkan-stream#4]
Hi ,

On MacOS,  there is a compile error with below.
"asio_c" is not found the project.
Please help to take a look at this issue.

Thanks 
ly gao

ll@MBDR4F6QHWQ9 vulkan-stream % ./build.sh      
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 195, in <module>
    main=import_build(os.getcwd(), external=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 54, in import_build
    mod=import_module_from_file("Buildfile.py", globals_aux = globals())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/tools/utils.py", line 45, in import_module_from_file
    spec.loader.exec_module(mod) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/Buildfile.py", line 4, in <module>
    conn=import_build("../asio_c")
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 51, in import_build
    with cwd_ctx(path):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/tools/utils.py", line 10, in cwd_ctx
    os.chdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '../asio_c'
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 195, in <module>
    main=import_build(os.getcwd(), external=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 54, in import_build
    mod=import_module_from_file("Buildfile.py", globals_aux = globals())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/tools/utils.py", line 45, in import_module_from_file
    spec.loader.exec_module(mod) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/Buildfile.py", line 4, in <module>
    conn=import_build("../asio_c")
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 51, in import_build
    with cwd_ctx(path):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/tools/utils.py", line 10, in cwd_ctx
    os.chdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '../asio_c'
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 195, in <module>
    main=import_build(os.getcwd(), external=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 54, in import_build
    mod=import_module_from_file("Buildfile.py", globals_aux = globals())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/tools/utils.py", line 45, in import_module_from_file
    spec.loader.exec_module(mod) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/Buildfile.py", line 4, in <module>
    conn=import_build("../asio_c")
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 51, in import_build
    with cwd_ctx(path):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/tools/utils.py", line 10, in cwd_ctx
    os.chdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '../asio_c

**Comment by DUOLabs333** [comment]
Ah, yes --- that's another project of mine you have to clone. I'll add it to the build instructions.

**Comment by niogaoly** [comment]
This project is great, thank you very much for your response

**Comment by DUOLabs333** [comment]
Oh, did you get it to work?

**Comment by niogaoly** [comment]
There are still many compilation errors


`Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/parse/parse.py", line 10, in <module>
    vk=ET.parse(os.path.join(VK_HEADER_PATH,"registry/vk.xml")).getroot()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ly.gao/work/emulator/vulkan-stream/tools/external/Vulkan-Headers/registry/vk.xml'
REQUESTED: Building target autogen...
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/utils.py", line 17, in <module>
    parsed=json.load(open("../parse/parsed.json"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../parse/parsed.json'
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/Commands.py", line 1, in <module>
    from utils import *
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/utils.py", line 17, in <module>
    parsed=json.load(open("../parse/parsed.json"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../parse/parsed.json'
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/Serialization.py", line 1, in <module>
    from utils import *
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/utils.py", line 17, in <module>
    parsed=json.load(open("../parse/parsed.json"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../parse/parsed.json'
DEPENDENCY: Building target library...
utils.cpp:62:27: fatal error: no member named 'format' in namespace 'std'
                auto format_string=std::format("Error opening the disk {}", path);
                                   ~~~~~^
1 error generated.
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 202, in <module>
    build_target("REQUESTED", target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 143, in build_target
    compile_target(target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 104, in compile_target
    target.INCLUDE_PATHS[i]=build_target("DEPENDENCY", e).CWD
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 172, in build_target
    os.utime(object_file, (modified_time, modified_time))
FileNotFoundError: [Errno 2] No such file or directory
DEPENDENCY: Building target library...
utils.cpp:62:27: fatal error: no member named 'format' in namespace 'std'
                auto format_string=std::format("Error opening the disk {}", path);
                                   ~~~~~^
1 error generated.
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 202, in <module>
    build_target("REQUESTED", target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 143, in build_target
    compile_target(target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 104, in compile_target
    target.INCLUDE_PATHS[i]=build_target("DEPENDENCY", e).CWD
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 172, in build_target
    os.utime(object_file, (modified_time, modified_time))
FileNotFoundError: [Errno 2] No such file or directory
`

**Comment by niogaoly** [comment]
There are still many compilation errors


Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/parse/parse.py", line 10, in <module>
    vk=ET.parse(os.path.join(VK_HEADER_PATH,"registry/vk.xml")).getroot()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ly.gao/work/emulator/vulkan-stream/tools/external/Vulkan-Headers/registry/vk.xml'
REQUESTED: Building target autogen...
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/utils.py", line 17, in <module>
    parsed=json.load(open("../parse/parsed.json"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../parse/parsed.json'
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/Commands.py", line 1, in <module>
    from utils import *
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/utils.py", line 17, in <module>
    parsed=json.load(open("../parse/parsed.json"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../parse/parsed.json'
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/Serialization.py", line 1, in <module>
    from utils import *
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/autogen/utils.py", line 17, in <module>
    parsed=json.load(open("../parse/parsed.json"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../parse/parsed.json'
DEPENDENCY: Building target library...
utils.cpp:62:27: fatal error: no member named 'format' in namespace 'std'
                auto format_string=std::format("Error opening the disk {}", path);
                                   ~~~~~^
1 error generated.
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 202, in <module>
    build_target("REQUESTED", target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 143, in build_target
    compile_target(target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 104, in compile_target
    target.INCLUDE_PATHS[i]=build_target("DEPENDENCY", e).CWD
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 172, in build_target
    os.utime(object_file, (modified_time, modified_time))
FileNotFoundError: [Errno 2] No such file or directory
DEPENDENCY: Building target library...
utils.cpp:62:27: fatal error: no member named 'format' in namespace 'std'
                auto format_string=std::format("Error opening the disk {}", path);
                                   ~~~~~^
1 error generated.
Traceback (most recent call last):
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 202, in <module>
    build_target("REQUESTED", target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 143, in build_target
    compile_target(target)
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 104, in compile_target
    target.INCLUDE_PATHS[i]=build_target("DEPENDENCY", e).CWD
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ly.gao/work/emulator/vulkan-stream/vulkan-stream/../tools/build.py", line 172, in build_target
    os.utime(object_file, (modified_time, modified_time))
FileNotFoundError: [Errno 2] No such file or directory

**Comment by DUOLabs333** [comment]
Right --- sorry, I (unreasonably) assumed that you downloaded all of the dependencies. I'll push an update that will automatically download the dependencies (though you'll need to set  UPDATE_DEPENDENCIES to 1).

**Comment by niogaoly** [comment]
This is my directory structure，No directory "parse"
![image](https://github.com/user-attachments/assets/e6a2f718-3962-4ebb-acdb-bfa2e7831181)

**Comment by niogaoly** [comment]
This is my directory structure, No direcoty "parse".

![1f4f5931-ca37-47c6-853e-21b6dbe3a68f](https://github.com/user-attachments/assets/c43a6c71-ccca-4e20-92cd-63769f4a14aa)

**Comment by DUOLabs333** [comment]
build.py should be run inside the vulkan-stream directory.

**Comment by DUOLabs333** [comment]
I updated the vulkan-stream repo (it turns out I had some commits locally that I forgot to push), as well as tools. Run `build.sh`, and everything *should* work. Let me know if something breaks.
