### ISSUE TITLE
Issues Compiling and Running vulkan-stream on macOS and Linux

### ISSUE THREAD

**Issue by Zackery12138** [DUOLabs333/vulkan-stream#5]
Hello,

I have encountered several issues while trying to compile and run the vulkan-stream project on both macOS (as the server) and Linux (as the client). Below is a detailed description of the problems and steps I took.

**Environment:**
Server (macOS):

- Vulkan SDK version: 1.3.280.1 (installed via LunarG)
- MoltenVK version: 1.2.7
- Compiler: Apple clang version 15.0.0

 Client (Linux):

- Linux distribution: Ubuntu 20.04 (Focal)
- Vulkan SDK version: 1.3.283.0 (installed via LunarG)
- Steps to Reproduce:

Setup and Build on macOS (Server):
Cloned the necessary repositories (vulkan-stream, tools, and asio_c) in the same parent directory.
Successfully built the project using ./build.sh, resulting in the vulkan_stream executable.

Setup on Linux (Client):
Installed the Vulkan SDK using the following commands:

```
wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.283-focal.list https://packages.lunarg.com/vulkan/1.3.283/lunarg-vulkan-1.3.283-focal.list
sudo apt update
sudo apt install vulkan-sdk
```
Ensured vulkaninfo command runs successfully, confirming Vulkan installation.
Attempt to Run on Linux (Client):
Executed the following command:

VK_ICD_FILENAMES=./stream_icd.aarch64.json <application>
Issues and Errors:

Missing ICD file and incorrect library_path:
The ICD JSON file stream_icd.aarch64.json points to a library_path (/home/system/Repos/vulkan-stream/vulkan_stream.so) that does not exist. The build process on macOS only creates an executable (vulkan_stream) and not a .so file.
ICD file content:

```
{
    "ICD": {
        "api_version": "1.1.255",
        "library_path": "/home/system/Repos/vulkan-stream/vulkan_stream.so"
    },
    "file_format_version": "1.0.0"
}
```
I assume this path is your local path, right? But I didn't get this .so file after compiling on my Mac. Do I need to compile it again on Linux?

**Request for Assistance:**

How should the project be set up and compiled for both server and client environments, especially regarding shared library (.so) generation?

Documentation Updates:
More detailed setup instructions in the README please, including environment variables and specific configuration steps.

Thank you for your time and help!

**Comment by DUOLabs333** [comment]
Oh, right ---- yeah, all you need to do is rename the library path in the file to point to your library. I'll update build.py to modify the JSON automatically.

The .so is only built for clients, so there's nothing to worry about.

**Comment by DUOLabs333** [comment]
I just pushed an update --- try again now.

**Comment by Zackery12138** [comment]
Thank you for the reply.
I understand that the .so file is built for the client, but my question is: after compiling on the Mac, should the .so file be generated, or do I need to compile it again on Linux? I successfully built the project on my Mac, but I couldn't find the .so file in my local directory.

**Comment by DUOLabs333** [comment]
The shared library is only for the client --- if your MacBook is acting as the server, then all you need is the executable.

**Comment by Zackery12138** [comment]
Thank you for the response. To clarify, I understand that the shared library (.so) is for the client（Linux）. My question is about the process to generate this vulkan_stream.so file.

When I build the project on my Mac (acting as the server), I don't see the .so file being generated. Should the .so file be generated during the Mac(server) build process, or do I need to compile the project again on the Linux client to generate the .so file?

Currently, after building on my Mac, I only see the executable and not the .so file.

**Comment by DUOLabs333** [comment]
Oh, I see the confusion. Yes, the project should be compiled again on the Linux guest to generate the so file --- the build tool automatically decides what to build based on the OS it's running on.

That's a valid question --- I'll update the README to clarify.

**Comment by Zackery12138** [comment]
Thanks, it helps, but I got a weird problem while compiling the project on Linux. I didn't face this issue when compiling on macOS. The problem seems to be related to the Glaze library. Here is the detailed error message:
```
zackery.cai@4CE212BZSN:~/Desktop/linuxvulkanstream/vulkan-stream$ ./build.sh 
WARNING: Action download is already completed for dependency asio. Skipping...
WARNING: Action build does not exist for dependency asio! Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency boost. Skipping...
WARNING: Action build does not exist for dependency boost! Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency glaze. Skipping...
WARNING: Action build does not exist for dependency glaze! Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
REQUESTED: Building target parse...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency asio. Skipping...
WARNING: Action build does not exist for dependency asio! Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency boost. Skipping...
WARNING: Action build does not exist for dependency boost! Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency glaze. Skipping...
WARNING: Action build does not exist for dependency glaze! Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
REQUESTED: Building target autogen...
WARNING: Action build does not exist for dependency asio! Skipping...
WARNING: Action download is already completed for dependency asio. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency boost! Skipping...
WARNING: Action download is already completed for dependency boost. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency glaze! Skipping...
WARNING: Action download is already completed for dependency glaze. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
DEPENDENCY: Building target library...
DEPENDENCY: Building target library...
REQUESTED: Cleaning target main...
WARNING: Action download is already completed for dependency asio. Skipping...
WARNING: Action build does not exist for dependency asio! Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency lz4. Skipping...
WARNING: Action build is already completed for dependency lz4. Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency shm_open_anon. Skipping...
WARNING: Action build does not exist for dependency shm_open_anon! Skipping...
WARNING: Action download is already completed for dependency Vulkan_Headers. Skipping...
WARNING: Action build does not exist for dependency Vulkan_Headers! Skipping...
WARNING: Action download is already completed for dependency boost. Skipping...
WARNING: Action build does not exist for dependency boost! Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency simdjson. Skipping...
WARNING: Action build does not exist for dependency simdjson! Skipping...
WARNING: Action download is already completed for dependency glaze. Skipping...
WARNING: Action build does not exist for dependency glaze! Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
WARNING: Action download is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action build is already completed for dependency Turbo_Base64. Skipping...
WARNING: Action download is already completed for dependency xxHash_3. Skipping...
WARNING: Action build is already completed for dependency xxHash_3. Skipping...
DEPENDENCY: Building target library...
DEPENDENCY: Building target library...
REQUESTED: Building target main...
In file included from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/core/meta.hpp:8,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/api/hash.hpp:9,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/api/std/span.hpp:8,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/core/read.hpp:8,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/binary/skip.hpp:8,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/binary/read.hpp:7,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/binary/ptr.hpp:6,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/binary.hpp:7,
                 from /home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/glaze.hpp:35,
                 from src/Server.cpp:1:
/home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/reflection/get_name.hpp: In instantiation of ‘constexpr const string_view glz::detail::get_name_impl<0, glz::detail::GLAZE_REFLECTOR>’:
/home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/reflection/get_name.hpp:61:36:   required from here
/home/zackery.cai/Desktop/linuxvulkanstream/tools/external/glaze/include/glaze/reflection/get_name.hpp:48:108: error: no matching function for call to ‘mangled_name<glz::detail::get_ptr<0, const glz::detail::GLAZE_REFLECTOR&>(glz::detail::external<glz::detail::GLAZE_REFLECTOR>)>()’
   48 | :string_view get_name_impl = mangled_name<get_ptr<N>(external<std::remove_volatile_t<T>>)>();
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

compilation terminated due to -Wfatal-errors.
Traceback (most recent call last):
  File "/home/zackery.cai/Desktop/linuxvulkanstream/vulkan-stream/../tools/build.py", line 211, in <module>
    build_target("REQUESTED", target)
  File "/home/zackery.cai/Desktop/linuxvulkanstream/vulkan-stream/../tools/build.py", line 181, in build_target
    os.utime(object_file, (modified_time, modified_time))
FileNotFoundError: [Errno 2] No such file or directory
```

I have already tried the following steps without success:

Ensured CMake and all dependencies are correctly installed.
Updated the Glaze library to the latest version.
Successfully built Glaze separately with make.

**Comment by DUOLabs333** [comment]
Hmmm, I'm not sure how that could even happen. What compiler are you using?

**Comment by Zackery12138** [comment]
gcc (Ubuntu 10.5.0-1ubuntu1 20.04) 10.5.0

g++ (Ubuntu 10.5.0-1ubuntu1 20.04) 10.5.0
Still not working, so confused

**Comment by DUOLabs333** [comment]
What version of glaze are you using?

**Comment by Zackery12138** [comment]
project(
    glaze
    VERSION 2.6.0
    LANGUAGES CXX
)
The glaze is downloaded through the code in Formulafile.py:
class glaze:
    def download(cls):
        git_clone("stephenberry/glaze", branch="v2.6.0")

**Comment by DUOLabs333** [comment]
Hmmm... could you see if you can get g++ 14 --- g++ 10 doesn't fully support C++20, especially concerning template argument deduction.

**Comment by Zackery12138** [comment]
Great! I finally got it to compile on my client side, but when I executed it with the command VK_ICD_FILENAMES=./stream_icd.aarch64.json ~/Desktop/vkcube, it seems like the Vulkan instantiation failed. I used the env command to debug and got the following output:
```
zackery.cai@4CE212BZSN:\~/Desktop/linuxvulkanstream/vulkan-stream$ export VK_LOADER_DEBUG=all
zackery.cai@4CE212BZSN:\~/Desktop/linuxvulkanstream/vulkan-stream$ env 
VK_ICD_FILENAMES=~/Desktop/linuxvulkanstream/vulkan-stream/stream_icd.aarch64.json ~/Desktop/vkcube
INFO:              Vulkan Loader Version 1.3.283
LAYER:             Searching for implicit layer manifest files
LAYER:                In following locations:
LAYER:                   /home/zackery.cai/.config/vulkan/implicit_layer.d
LAYER:                   /etc/xdg/xdg-ubuntu/vulkan/implicit_layer.d
LAYER:                   /etc/xdg/vulkan/implicit_layer.d
LAYER:                   /etc/vulkan/implicit_layer.d
LAYER:                   /home/zackery.cai/.local/share/vulkan/implicit_layer.d
LAYER:                   /usr/share/ubuntu/vulkan/implicit_layer.d
LAYER:                   /usr/local/share/vulkan/implicit_layer.d
LAYER:                   /usr/share/vulkan/implicit_layer.d
LAYER:                   /var/lib/snapd/desktop/vulkan/implicit_layer.d
LAYER:                Found the following files:
LAYER:                   /etc/vulkan/implicit_layer.d/nvidia_layers.json
LAYER:                   /usr/share/vulkan/implicit_layer.d/VkLayer_MESA_device_select.json
INFO:              Found manifest file /etc/vulkan/implicit_layer.d/nvidia_layers.json (file version 1.0.0)
WARNING | LAYER:   loader_add_layer_properties: 'layers' tag not supported until file version 1.0.1, but /etc/vulkan/implicit_layer.d/nvidia_layers.json is reporting version 1
INFO:              Found manifest file /usr/share/vulkan/implicit_layer.d/VkLayer_MESA_device_select.json (file version 1.0.0)
DRIVER:            Searching for driver manifest files
DRIVER:               In following locations:
DRIVER:                  /home/zackery.cai/Desktop/linuxvulkanstream/vulkan-stream/stream_icd.aarch64.json
DRIVER:               Found the following files:
DRIVER:                  /home/zackery.cai/Desktop/linuxvulkanstream/vulkan-stream/stream_icd.aarch64.json
DRIVER:            Found ICD manifest file /home/zackery.cai/Desktop/linuxvulkanstream/vulkan-stream/stream_icd.aarch64.json, version 1.0.0
DEBUG | DRIVER:    Searching for ICD drivers named /home/zackery.cai/Desktop/linuxvulkanstream/vulkan-stream/vulkan_stream.so
Executing vkGetInstanceProcAddr
VkInstance handle is NULL, serializing to (nil)...
VkInstance handle is NULL, serializing to (nil)...
```
I'm not sure what is wrong. I believe I’ve got all the configuration and dependencies of vulkan_stream.so in place. I’m running this on Ubuntu 20.04.6 LTS, with Vulkan Loader version 1.3.283. Other Vulkan applications work correctly if I run them directly, so I’m wondering if there’s something I’m missing with the ICD setup or if there could be an issue with how the Vulkan loader interacts with vulkan_stream.so.

Any advice on what I should check or try next would be greatly appreciated.

**Comment by DUOLabs333** [comment]
Ok, I'll update the README to detail minimum compiler versions.

Before running vkcube, did you make sure vulkan_stream is running on the server side?

**Comment by DUOLabs333** [comment]
You should also make sure that STREAM_ADDRESS and STREAM_PORT point to an address that's reachable by both the client and server.
